name: Test Target Branch

# This needs to fail if a PR is submitted with the target branch as master
on:
  pull_request:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Fail the check so it alerts the author and maintainers
      - name: Not Good
        run: exit 1
