name: Validate Target Branch
on: [pull_request]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Target branch should be development
        shell: pwsh
        if: github.base_ref != 'refs/heads/development'
        run: |
          echo "Base ref is $env:GITHUB_BASE_REF"
          echo "Head
          throw "Target branch set to $env:GITHUB_BASE_REF and not development"
