name: Validate Target Branch
on: [pull_request]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Target branch should be development
        shell: pwsh
        run: |
          Write-Host "Base ref is $($GITHUB_BASE_REF)"
          if ($GITHUB_BASE_REF -ne 'refs/heads/development') {
            throw "Target branch set to $($GITHUB_BASE_REF) and not development"
          } else {
            Write-Output "Target branch set to $($GITHUB_BASE_REF)"
          }
